sophie/add_sem86_to_namespace
THIS-Institute/thiscovery-lib pull request #7
Opened 2021-12-13 16:50 UTC by sophiemachin

2021-12-13 17:23 UTC, afs25 requested changes
I think we should take the opportunity to move that config dictionary from this file to dev_config.py. Let's discuss tomorrow.

2021-12-13 17:23 UTC, afs25 commented on thiscovery_lib/utilities.py
>          }
Let's move this to dev_config.py?

2021-12-14 15:12 UTC, this-andy commented on thiscovery_lib/utilities.py
>          }
Agreed that Sophie/Andre will do this

2021-12-17 17:48 UTC, afs25 requested changes
See inline comment.

2021-12-17 17:48 UTC, afs25 commented on thiscovery_lib/utilities.py
> +from local.dev_config import namespace2env_var_name  # set environment variables
We cannot do this because utilities.py is used by AWS lambdas and there is no local.dev_config.py file in the lambda deployment package.

So, what we will have to do instead is:
- move namespace2env_var_name to secrets.py instead of dev_config.py (I think that makes more sense considering current usage of those files)
- we can take this opportunity to simplify things a bit and instead of mapping /prod/ to THISCOVERY_PROD_PROFILE (a variable that holds the profile name), let's map /prod/ to the profile name directly (i.e. map it to <account_number_here>_AdministratorAccess)
- serialise namespace2env_var_name as a json string using json.dumps()
- place that string in a environment variable using os.environ

Then we can adapt the code here in utilities.py:
- we don't need to add any imports
- desserialise the environment variable to convert it back to a dict (using json.loads()) 
- lookup the dict using namespace and return the value

We can discuss these changes in a call if needed.

2021-12-20 16:54 UTC, merged